#!/usr/bin/env python3
# Generate src/embedded_shaders.hpp from the compiled SPIR-V in build/spv/.
# CLEAN: this embeds ONLY win-fg's own shaders (of3_* optical flow + wfg_synth).
# There is no traced shader table and no third-party compiled artifact here.
import sys, pathlib

SHADERS = [
    "of3_luma", "of3_downsample", "of3_flow", "of3_expand",
    "of3_flow_m4", "of3_expand_m4",
    "of3_gm_reduce", "of3_gm_prewarp",   # C1 global-motion pre-warp
    "wfg_synth",
]

def emit(spv_dir: pathlib.Path, out: pathlib.Path):
    lines = [
        "// GENERATED by tools/embed_spv.py — do not edit by hand.",
        "// win-fg embedded SPIR-V: our optical-flow front end + synthesis only.",
        "#pragma once",
        "#include <cstdint>",
        "#include <cstddef>",
        "namespace winfg { namespace embedded {",
    ]
    ids = []
    for name in SHADERS:
        data = (spv_dir / f"{name}.spv").read_bytes()
        assert len(data) % 4 == 0, f"{name}.spv not word-aligned"
        assert data[:4] == b"\x03\x02\x23\x07", f"{name}.spv bad SPIR-V magic"
        words = [int.from_bytes(data[i:i+4], "little") for i in range(0, len(data), 4)]
        ident = name.upper()
        ids.append((name, ident))
        body = ",".join(f"0x{w:08x}u" for w in words)
        lines.append(f"static const uint32_t {ident}_SPV[] = {{{body}}};")
        lines.append(f"static const size_t  {ident}_LEN = {len(words)};")
    # simple accessor by logical name
    lines.append("struct Blob { const uint32_t* code; size_t words; };")
    lines.append("enum Shader { " + ", ".join(i for _, i in ids) + ", SHADER_COUNT };")
    lines.append("static inline Blob blob(Shader s) {")
    lines.append("  switch (s) {")
    for name, ident in ids:
        lines.append(f"    case {ident}: return {{ {ident}_SPV, {ident}_LEN }};")
    lines.append("    default: return { nullptr, 0 };")
    lines.append("  }")
    lines.append("}")
    lines.append("} } // namespace winfg::embedded")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(SHADERS)} shaders)")

if __name__ == "__main__":
    root = pathlib.Path(__file__).resolve().parents[1]
    emit(root / "build" / "spv", root / "src" / "embedded_shaders.hpp")
